# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('category', models.IntegerField(choices=[(1, 'Conferencia'), (2, 'Seminario'), (3, 'Congreso'), (4, 'Curso')], verbose_name='Categor\xeda')),
                ('type', models.IntegerField(choices=[(1, 'Conferencia'), (2, 'Seminario'), (3, 'Congreso'), (4, 'Curso')], verbose_name='Tipo de evento')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direcci\xf3n')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de t\xe9rmino')),
                ('register_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
            ],
        ),
    ]
