# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Conferencia', 'Conferencia'), ('Seminario', 'Seminario'), ('Congreso', 'Congreso'), ('Curso', 'Curso')], max_length=50, verbose_name='Categor\xeda'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=50, verbose_name='Tipo de evento'),
        ),
    ]
